# Конфигурационный файл

SAVE_FILE = 'config.json' # Файл для бэкапа конфига
TOKEN = 'XXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXX' # Токен бота (не трогать и не распространять!!)
BOT_ID = '5578358002' # ID бота
ADMINS_ID = ['1380351533'] # ID юзеров, от которых будут выполняться команды в ЛС (ИЗМЕНИТЬ, Я ДОБАВИЛ СВОЙ)
CAPTCHA_TIME = 60 # Время ожидания каптчи(в секундах)

# Словарь с каптчей и её значениями
# При желании словарь может дополняться отсюда: https://carpedm20.github.io/emoji/
# Но лучше оставить всё, как есть, т.к. эмодзи не должны быть похожи
CAPTCHA = {
':airplane:': 'Самолёт',
':alarm_clock:': 'Будильник',
':anchor:': 'Якорь',
':ant:': 'Муравей',
':automobile:': 'Машина',
':avocado:': 'Авокадо',
':axe:': 'Топор',
':backpack:': 'Рюкзак',
':bacon:': 'Бекон',
':balance_scale:': 'Весы',
':balloon:': 'Шарик',
':banana:': 'Банан',
':bathtub:': 'Ванна',
':bear:': 'Медведь',
':bed:': 'Кровать',
':beetle:': 'Жук',
':bell:': 'Колокол',
':bicycle:': 'Велосипед',
':billed_cap:': 'Кепка',
':birthday_cake:': 'Торт',
':black_cat:': 'Кот',
':blossom:': 'Цветок',
':blowfish:': 'Рыба',
':blue_book:': 'Книга',
':blueberries:': 'Черника',
':boar:': 'Кабан',
':bomb:': 'Бомба',
':bone:': 'Кость',
':boomerang:': 'Бумеранг',
':brain:': 'Мозг',
':bread:': 'Хлеб',
':brick:': 'Кирпич',
':briefcase:': 'Портфель',
':briefs:': 'Плавки',
':broom:': 'Метла',
':bucket:': 'Ведро',
':bug:': 'Гусеница',
':bullseye:': 'Мишень',
':bus:': 'Автобус',
':butterfly:': 'Бабочка',
':cactus:': 'Кактус',
':calendar:': 'Календарь',
':camera:': 'Камера',
':candy:': 'Конфета',
':carrot:': 'Морковь',
':castle:': 'Замок',
':chains:': 'Цепи',
':chair:': 'Стул',
':cheese_wedge:': 'Сыр',
':cherries:': 'Вишня',
':chess_pawn:': 'Пешка',
':chipmunk:': 'Бурундук',
':chocolate_bar:': 'Шоколадка',
':clown_face:': 'Клоун',
':club_suit:': 'Крести',
':coat:': 'Куртка',
':cockroach:': 'Таракан',
':coconut:': 'Кокос',
':coin:': 'Монета',
':collision:': 'Взрыв',
':compass:': 'Компас',
':cookie:': 'Печенье',
':cow_face:': 'Корова',
':crab:': 'Краб',
':credit_card:': 'Кредитка',
':whale:': 'Кит',
':volcano:': 'Вулкан',
':up_arrow:': 'Вверх',
':unlocked:': 'Замок',
':umbrella:': 'Зонт',
':turtle:': 'Черепаха',
':triangular_flag:': 'Флажок',
':tractor:': 'Трактор',
':tomato:': 'Томат',
':tornado:': 'Торнадо',
':thread:': 'Катушка',
':tent:': 'Палатка',
':telescope:': 'Телескоп',
':telephone:': 'Телефон',
':teapot:': 'Чайник',
':t-shirt:': 'Футболка',
':syringe:': 'Шприц',
':sweat_droplets:': 'Капли',
':sunflower:': 'Подсолнух',
':sun:': 'Солнце',
':star:': 'Звезда',
':spider_web:': 'Паутина',
':spider:': 'Паук',
':spade_suit:': 'Пики',
':snowflake:': 'Снежинка',
':snake:': 'Змея',
':snail:': 'Улитка',
':skull:': 'Череп',
':shrimp:': 'Креветка',
':shorts:': 'Шорты',
':shield:': 'Щит',
':shark:': 'Акула',
':scissors:': 'Ножницы',
':zebra:': 'Зебра',
':lipstick:': 'Помада'
}

blacklist = set() # Чёрный список для ссылок
non_authorized = {} # Словарь для тех, кого ожидает каптча. Его ключи используются как список ID всех чатов.
last_messages = {} # Cловарь стеков последних (5) сообщений
usernames = {} # Словарь с именами всех пользователей вида username: id
post_chats = set() # Множество выбранных чатов для рассылки поста
silenced_chats = set() # Множество с заглушёнными чатами
